-- CREATE METERS TABLE
CREATE TABLE IF NOT EXISTS meters (
    id SERIAL PRIMARY KEY,
    serial_id TEXT NOT NULL,
    label TEXT NOT NULL,
    connected_address TEXT NOT NULL,
    connected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
