CREATE TABLE IF NOT EXISTS readings (
    id SERIAL PRIMARY KEY,
    meter_id INTEGER 
        REFERENCES meters(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    reading_value INTEGER NOT NULL,
    reading_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
